name: Build APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3.10 python3.10-distutils git zip openjdk-17-jdk unzip wget autoconf automake libtool

        # Installer pip, setuptools et wheel pour Python 3.10
        python3.10 -m ensurepip --upgrade
        python3.10 -m pip install --upgrade pip setuptools wheel

    - name: Install Android NDK 25b
      run: |
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip
        sudo mv android-ndk-r25b /usr/local/lib/android/sdk/ndk

    - name: Install Buildozer
      run: |
        python3.10 -m pip install buildozer cython

    - name: Build APK
      run: |
        python3.10 -m buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
